name: Jeeeeeeeeen
description: Still waters run deep.
keywords: front-end notes

url: http://imjeen.github.io/notes
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: false
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: article
   url: /articles
 - title: About
   url: /about
